#!/usr/bin/env python3
"""Generate secure secrets for MedAI Compass deployment.

This script generates cryptographically secure secrets for:
- POSTGRES_PASSWORD
- REDIS_PASSWORD
- JWT_SECRET
- PHI_ENCRYPTION_KEY (Fernet-compatible)

Usage:
    python scripts/generate_secrets.py [--output .env] [--force]
"""

import argparse
import secrets
import base64
import os
from pathlib import Path
from cryptography.fernet import Fernet


def generate_password(length: int = 32) -> str:
    """Generate a secure random password."""
    return secrets.token_urlsafe(length)


def generate_jwt_secret(length: int = 64) -> str:
    """Generate a secure JWT secret."""
    return secrets.token_hex(length)


def generate_fernet_key() -> str:
    """Generate a Fernet encryption key for PHI."""
    return Fernet.generate_key().decode()


def generate_all_secrets() -> dict:
    """Generate all required secrets."""
    return {
        "POSTGRES_PASSWORD": generate_password(24),
        "REDIS_PASSWORD": generate_password(24),
        "JWT_SECRET": generate_jwt_secret(32),
        "PHI_ENCRYPTION_KEY": generate_fernet_key(),
    }


def load_existing_env(env_path: Path) -> dict:
    """Load existing .env file if it exists."""
    env_vars = {}
    if env_path.exists():
        with open(env_path, "r") as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith("#") and "=" in line:
                    key, _, value = line.partition("=")
                    # Remove quotes if present
                    value = value.strip().strip('"').strip("'")
                    env_vars[key.strip()] = value
    return env_vars


def write_env_file(env_path: Path, env_vars: dict, secrets: dict) -> None:
    """Write secrets to .env file, preserving existing variables."""
    # Merge: existing vars + new secrets (secrets don't overwrite if already set)
    for key, value in secrets.items():
        if key not in env_vars or not env_vars[key]:
            env_vars[key] = value
            print(f"  ✓ Generated: {key}")
        else:
            print(f"  → Kept existing: {key}")
    
    # Write the .env file
    with open(env_path, "w") as f:
        f.write("# MedAI Compass Environment Configuration\n")
        f.write("# Auto-generated secrets - DO NOT COMMIT TO VERSION CONTROL\n")
        f.write("#\n")
        f.write("# Generated by: python scripts/generate_secrets.py\n")
        f.write("#\n\n")
        
        # Group variables by category
        categories = {
            "Database": ["POSTGRES_HOST", "POSTGRES_PORT", "POSTGRES_USER", "POSTGRES_PASSWORD", "POSTGRES_DB"],
            "Redis": ["REDIS_HOST", "REDIS_PORT", "REDIS_PASSWORD"],
            "Security": ["JWT_SECRET", "PHI_ENCRYPTION_KEY"],
            "API": ["API_HOST", "API_PORT", "CORS_ORIGINS", "ENVIRONMENT", "LOG_LEVEL", "DEBUG"],
            "HuggingFace": ["HF_TOKEN", "HUGGING_FACE_HUB_TOKEN"],
            "Modal (Cloud GPU)": ["MODAL_TOKEN_ID", "MODAL_TOKEN_SECRET"],
            "Storage": ["MINIO_ACCESS_KEY", "MINIO_SECRET_KEY", "MINIO_ENDPOINT"],
            "Monitoring": ["GRAFANA_PASSWORD"],
            "Datasets": ["PHYSIONET_USERNAME", "PHYSIONET_PASSWORD"],
            "Other": [],
        }
        
        written_keys = set()
        
        for category, keys in categories.items():
            category_vars = {k: env_vars[k] for k in keys if k in env_vars}
            if category_vars:
                f.write(f"# {category}\n")
                for key, value in category_vars.items():
                    f.write(f'{key}="{value}"\n')
                    written_keys.add(key)
                f.write("\n")
        
        # Write any remaining variables
        other_vars = {k: v for k, v in env_vars.items() if k not in written_keys}
        if other_vars:
            f.write("# Other\n")
            for key, value in other_vars.items():
                f.write(f'{key}="{value}"\n')
    
    print(f"\n  ✓ Written to: {env_path}")


def create_env_example(project_root: Path) -> None:
    """Create .env.example file with all variable descriptions."""
    example_content = '''# MedAI Compass Environment Configuration
# Copy this file to .env and fill in the values
# Run: python scripts/generate_secrets.py to auto-generate secrets

# =============================================================================
# Database (PostgreSQL)
# =============================================================================
POSTGRES_HOST="localhost"
POSTGRES_PORT="5432"
POSTGRES_USER="medai"
POSTGRES_PASSWORD=""  # Auto-generated
POSTGRES_DB="medai_compass"

# =============================================================================
# Redis (Cache & Queues)
# =============================================================================
REDIS_HOST="localhost"
REDIS_PORT="6379"
REDIS_PASSWORD=""  # Auto-generated

# =============================================================================
# Security
# =============================================================================
JWT_SECRET=""  # Auto-generated (64 hex chars)
PHI_ENCRYPTION_KEY=""  # Auto-generated (Fernet key for HIPAA PHI encryption)

# =============================================================================
# API Configuration
# =============================================================================
API_HOST="0.0.0.0"
API_PORT="8000"
CORS_ORIGINS="*"  # Set specific origins in production
ENVIRONMENT="development"  # development, staging, production
LOG_LEVEL="INFO"
DEBUG="false"

# =============================================================================
# HuggingFace (Required for MedGemma models)
# =============================================================================
# Get token from: https://huggingface.co/settings/tokens
# Ensure you have accepted the MedGemma license
HF_TOKEN=""
HUGGING_FACE_HUB_TOKEN=""  # Alternative name

# =============================================================================
# Modal (Cloud GPU - Recommended for macOS/no local GPU)
# =============================================================================
# Get tokens by running: modal token new
MODAL_TOKEN_ID=""
MODAL_TOKEN_SECRET=""

# =============================================================================
# Object Storage (MinIO)
# =============================================================================
MINIO_ENDPOINT="localhost:9000"
MINIO_ACCESS_KEY="minioadmin"
MINIO_SECRET_KEY=""  # Set a secure value in production

# =============================================================================
# Monitoring
# =============================================================================
GRAFANA_PASSWORD="admin"  # Change in production

# =============================================================================
# Dataset Access (Optional)
# =============================================================================
# PhysioNet credentials for MIMIC datasets
# Register at: https://physionet.org/
PHYSIONET_USERNAME=""
PHYSIONET_PASSWORD=""

# =============================================================================
# TLS/HTTPS (Production)
# =============================================================================
# Domain for Let's Encrypt certificates
DOMAIN=""
ACME_EMAIL=""
'''
    
    example_path = project_root / ".env.example"
    with open(example_path, "w") as f:
        f.write(example_content)
    print(f"  ✓ Created: {example_path}")


def main():
    parser = argparse.ArgumentParser(
        description="Generate secure secrets for MedAI Compass"
    )
    parser.add_argument(
        "--output", "-o",
        type=str,
        default=".env",
        help="Output file path (default: .env)"
    )
    parser.add_argument(
        "--force", "-f",
        action="store_true",
        help="Overwrite existing secrets"
    )
    parser.add_argument(
        "--example-only",
        action="store_true",
        help="Only create .env.example file"
    )
    
    args = parser.parse_args()
    
    # Determine project root
    script_dir = Path(__file__).parent
    project_root = script_dir.parent
    
    print("\n" + "=" * 60)
    print("  MedAI Compass - Secret Generator")
    print("=" * 60 + "\n")
    
    # Always create/update .env.example
    create_env_example(project_root)
    
    if args.example_only:
        print("\n  Done (example only mode)")
        return
    
    # Generate secrets
    print("\nGenerating secrets...")
    new_secrets = generate_all_secrets()
    
    # Load existing .env if present
    env_path = project_root / args.output
    existing_env = load_existing_env(env_path)
    
    # Add default values for non-secret variables
    defaults = {
        "POSTGRES_HOST": "postgres",
        "POSTGRES_PORT": "5432",
        "POSTGRES_USER": "medai",
        "POSTGRES_DB": "medai_compass",
        "REDIS_HOST": "redis",
        "REDIS_PORT": "6379",
        "API_HOST": "0.0.0.0",
        "API_PORT": "8000",
        "CORS_ORIGINS": "*",
        "ENVIRONMENT": "development",
        "LOG_LEVEL": "INFO",
        "DEBUG": "false",
        "MINIO_ENDPOINT": "minio:9000",
        "MINIO_ACCESS_KEY": "minioadmin",
        "MINIO_SECRET_KEY": "minioadmin123",
        "GRAFANA_PASSWORD": "admin",
    }
    
    for key, value in defaults.items():
        if key not in existing_env:
            existing_env[key] = value
    
    # Handle force flag
    if args.force:
        print("  (Force mode: overwriting all secrets)")
        existing_env.update(new_secrets)
        write_env_file(env_path, existing_env, {})
    else:
        write_env_file(env_path, existing_env, new_secrets)
    
    # Security reminder
    print("\n" + "-" * 60)
    print("  IMPORTANT SECURITY NOTES:")
    print("-" * 60)
    print("  1. Add .env to .gitignore (if not already)")
    print("  2. Never commit secrets to version control")
    print("  3. Use different secrets for each environment")
    print("  4. Back up production secrets securely")
    print("-" * 60 + "\n")
    
    # Check for HuggingFace token
    if not existing_env.get("HF_TOKEN") and not existing_env.get("HUGGING_FACE_HUB_TOKEN"):
        print("  ⚠ WARNING: HF_TOKEN not set!")
        print("    MedGemma models require a HuggingFace token.")
        print("    Get one at: https://huggingface.co/settings/tokens")
        print()
    
    # Check for Modal tokens
    if not existing_env.get("MODAL_TOKEN_ID"):
        print("  ℹ INFO: Modal tokens not set")
        print("    For cloud GPU access, run: modal token new")
        print()


if __name__ == "__main__":
    main()
